version: '3.1'

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: root
      POSTGRES_PASSWORD: development
    volumes:
      - ./database:/var/lib/postgresql/data
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    
