name: Check

on: [push, pull_request]
jobs:
  check:
    name: Lint Verification
    runs-on: ubuntu-latest
    steps:

      # checkout

      - name: Checkout
        uses: actions/checkout@v2

      # setup node
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # install deps
      - name: Install dependencies
        run: npm ci
  
      # checks lint
      - name: Check Lint
        run: npm run lint

      # tests

      - name: Run Tests
        run: npm run test
